[package]
name = "share_expenses_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web =  { version ="4.5.1"}
dotenvy = "0.15.7"
serde = "1.0.196"
serde_json = "1.0.113"
sqlx = {version = "0.7.3", features = ["runtime-tokio", "postgres", "json"]}
